[package]
name = "portaudio-sine"
version = "0.1.0"
authors = ["Bart Massey <bart@cs.pdx.edu>"]

[[bin]]
name = "nbsquare"
path = "src/nbsquare.rs"

[[bin]]
name = "bsquare"
path = "src/bsquare.rs"

[[bin]]
name = "bsine"
path = "src/bsine.rs"

[dependencies]
portaudio = "0.7.0"
